name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: ${{vars.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{vars.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name : Run tests
        run: |
          chmod +x mvnw
          ./mvnw test
        env:
          DB_USERNAME: ${{vars.DB_USERNAME}}
          DB_PASSWORD: ${{vars.DB_PASSWORD}}
          DB_URL: jdbc:postgresql://localhost:5432/MyRecipeAPI
          SPRING_PROFILES_ACTIVE: ${{vars.SPRING_PROFILES_ACTIVE}}

      - name : Package application
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myrecipe-api-jar
          path: target/*.jar

  docker-build:
    runs-on: self-hosted
    needs: build-test

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Build Docker image
        run: docker build -t myrecipe-api:${{github.sha}} .

  docker-push:
    runs-on: self-hosted
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/myrecipe-api:${{github.sha}} .

      - name: Push image
        run: docker push ${{secrets.DOCKER_USERNAME}}/myrecipe-api:${{github.sha}}

  deploy:
    runs-on: self-hosted
    needs: docker-push

    steps:
      - name: Deploy on server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          privatKey: ${{secrets.SERVER_SSH_KEY}}
          script: |
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
            docker pull ${{secrets.DOCKER_USERNAME}}/myrecipe-api:${{github.sha}}
            docker stop myrecipe-api || true
            docker rm myrecipe-api || true
            docker compose up -d
